Visualisation carom balls
ekiefl/pooltool pull request #169
Opened 2024-12-31 13:00 UTC by erdo100

Added:
- Carom billiard ball visualizations

Changed:
- standard size of balls
- standard size of table
- height of cushion nose

2024-12-31 19:08 UTC, ekiefl requested changes

2024-12-31 19:08 UTC, ekiefl commented on pooltool/models/table/carambol_match/carambol_match.blend
This file crashes Blender when I open it. It also isn't used anywhere. Can you please remove it? (git rm)

2024-12-31 19:08 UTC, ekiefl commented on Scripts/Ersin_table.py
Please remove this file and the directory `Scripts/`

2025-01-01 02:55 UTC, erdo100 commented on pooltool/models/table/carambol_match/carambol_match.blend
Removed folder and file

2025-01-01 02:56 UTC, erdo100 commented on Scripts/Ersin_table.py
Removed

2025-01-01 19:04 UTC, derek-mcblane commented on pooltool/objects/table/collection.py
> +        w=2.84 / 2,
What's the source for this dimension? I was under the impression that billiard tables were 120in x 60in.

2025-01-01 19:12 UTC, derek-mcblane commented on pooltool/objects/table/collection.py
> +        w=2.84 / 2,
I found 2.84 here https://files.umb-carom.org/Public/Rules/Carom_Rules.pdf

2025-01-01 19:13 UTC, ekiefl commented on pooltool/objects/table/collection.py
> +        w=2.84 / 2,
They are colloquially "10 foot" tables, but nose to nose dimensions are different (https://en.wikipedia.org/wiki/Billiard_table#Dimensions)

EDIT: ditto

2025-01-01 19:15 UTC, ekiefl commented on pooltool/objects/table/collection.py
> +        w=2.84 / 2,
I'm gonna add the wayback machine URL on wiki as the source.

2025-01-01 19:16 UTC, derek-mcblane commented on pooltool/objects/table/collection.py
> +        w=2.84 / 2,
Also here https://billiards.colostate.edu/faq/table/sizes/

2025-01-01 19:29 UTC, ekiefl approved these changes

2025-01-01 20:11 UTC, erdo100 commented on pooltool/objects/table/collection.py
> +        w=2.84 / 2,
Yes Derek, the UMB is the world governing federation, organizing world cups and championships.

2025-01-01 20:21 UTC, ekiefl commented
Congratulations @erdo100 on becoming a contributor of pooltool. Thanks for your contribution, and I hope you consider contributing more in the future. Merging now.

2025-01-01 20:22 UTC, merged